;; DO NOT EDIT THIS FILE!
;; Instead, add overrides to: config.scm
;;
;; Adapted from https://github.com/webyrd/mediKanren/blob/master/biolink/config.defaults.scm
((racket-binary-path . "/usr/local/bin/racket")
 (chez-binary-path . "/usr/local/bin/scheme")
 ;; UI-to-MCP connection
 (ui-tcp-ip-address . "localhost")
 (ui-tcp-port . 8081)
 ;; SCP-to-MCP connection
 (scp-tcp-ip-address . "localhost")
 (scp-tcp-port . 8082)
 (max-simultaneous-mcp/scp-connections . 5)
 ;;
 (enable-proxy-logging . #f)
 ;;
 (default-ui-language . "English")

 ;; Add configuration options as new association pairs.
 )
