;; DO NOT EDIT THIS FILE!
;; Instead, add overrides to: config.scm
;;
;; Adapted from https://github.com/webyrd/mediKanren/blob/master/biolink/config.defaults.scm
((racket-binary-path . "/usr/local/bin/racket")
 (chez-binary-path . "/usr/local/bin/scheme")
 (tcp-ip-address . "localhost")
 (tcp-port . 8081)
 (default-gui-language . "English")

 ;; Add configuration options as new association pairs.
 )
